<?php

/*

ARQUIVO DE CONFIGUTAÇÃO DO SISTEMA

ALTERE AS VARIÁVEIS DE ACORDO COM A SUA NESCESSIDADE.

RENOMEIE ESTE ARQUIVO PARA: configuration.php

*/


// ADICIONE AQUI A URL DO SISTEMA ERP
$CONFIG_URL = "http://200.195.141.44:30002/boletos/ws.php?wsdl";

?>